# Generated by Django 6.0.2 on 2026-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_agenda', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('gambar', models.ImageField(upload_to='agenda/')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='buku/')),
                ('kategori', models.CharField(choices=[('fiksi', 'Fiksi'), ('nonfiksi', 'Non-Fiksi')], default='fiksi', max_length=10)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumentasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='dokumentasi/')),
                ('tanggal_kegiatan', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
